workflows:
  android-debug:
    name: Android Debug Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        PACKAGE_NAME: "com.subguard"
      java: 17
    scripts:
      - name: Fix Gradle Permissions (Windows Fix)
        script: | 
          chmod +x gradlew
      - name: Build Android Debug APK
        script: | 
          ./gradlew assembleDebug
    artifacts:
      - app/build/outputs/apk/debug/*.apk